# Generated by Django 2.2.5 on 2019-10-15 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_mode', models.CharField(choices=[('PU', 'Per unit'), ('LS', 'Lump-sum')], default='PU', max_length=2, verbose_name='Calculation per unit or lump sum')),
                ('number', models.IntegerField(unique=True, verbose_name='Invoice number')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Invoice date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('working_period', models.CharField(max_length=50, verbose_name='Working period')),
                ('template', models.FileField(blank=True, null=True, upload_to='invoice_templates/', verbose_name='Invoice template for generation')),
                ('txt', models.CharField(blank=True, max_length=300, null=True, verbose_name='Invoice text')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Working hours')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hourly rate (paid per hour)')),
                ('net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net amount')),
                ('percent_tax', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tax in percent')),
                ('document', models.FileField(blank=True, null=True, upload_to='invoice_documents/', verbose_name='Stored invoice document')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year of service')),
                ('month', models.CharField(max_length=30, verbose_name='Month of service')),
                ('date_of_creation', models.DateField(blank=True, null=True, verbose_name='Created at')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total hours')),
                ('excel_document', models.FileField(upload_to='', verbose_name='Excel document with daily working hours')),
                ('template', models.FileField(upload_to='invoice_templates/', verbose_name='Word template for generation')),
                ('document', models.FileField(blank=True, null=True, upload_to='invoice_documents/', verbose_name='Generated document')),
            ],
        ),
    ]
